name: 'Generate SmartCity vector tiles'
description: 'generate pmtiles with tippeacanoe'
author: 'Geolonia'
inputs:
  INPUT_DIR:
    description: 'Input directory.'
    required: true
    default: './'

  MUNICIPALITY_CODE:
    description: '全国地方公共団体コード (5桁)'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_DIR: ${{ inputs.INPUT_DIR }}
    MUNICIPALITY_CODE: ${{ inputs.MUNICIPALITY_CODE }}
