name: 'Generate SmartCity vector tiles'
description: 'generate pmtiles with tippeacanoe'
author: 'Geolonia'
inputs:
  INPUT_DIR:
    description: 'Input directory.'
    required: true
    default: './'

  MUNICIPALITY_ID:
    description: 'ID to identify the City'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_DIR: ${{ inputs.INPUT_DIR }}
    MUNICIPALITY_ID: ${{ inputs.MUNICIPALITY_ID }}