name: 'Generate SmartCity vector tiles'
description: 'generate pmtiles with tippeacanoe'
author: 'Geolonia'
inputs:
  INPUT_DIR:
    description: 'Input directory.'
    required: true
    default: './'

  NAME:
    description: 'Geolonia SmartMap で表示するときの表示名'
    required: true
    default: 'Geolonia SmartMap サンプルマップ'

  MUNICIPALITY_CODE:
    description: '全国地方公共団体コード (5桁)'
    required: true

  DEPLOY_S3_BUCKET:
    description: 'デプロイ先の AWS S3 バケツ'
    required: true
    default: 'smartcitystandaloneinfra-smartcitystandaloneinfra-w7czadiwetse'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_DIR: ${{ inputs.INPUT_DIR }}
    TILESET_NAME: ${{ inputs.NAME }}
    MUNICIPALITY_CODE: ${{ inputs.MUNICIPALITY_CODE }}
    DEPLOY_S3_BUCKET: ${{ inputs.DEPLOY_S3_BUCKET }}
