on: [push]

jobs:
  build-tile:
    runs-on: ubuntu-latest
    name: Test this action
    permissions:
     contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: Run this action
        uses: geolonia/smartcity-data-upload-action@main
        with:
          input_dir: './docs'
          access_key: 'example-city'
          aws_access_key: 'example-access-key'
          aws_secret_access_key: 'example-secret-access-key'
          
