on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-tile:
    runs-on: ubuntu-latest
    name: Test this action
    permissions:
     contents: read
     id-token: write
     pages: write

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Run this action
        uses: ./
        with:
          INPUT_DIR: './docs'
          MUNICIPALITY_CODE: '37201'
          AWS_S3_BUCKET_NAME: 'smartcity-data-upload-action-dev'
