on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-tile:
    runs-on: ubuntu-latest
    name: Test this action

    permissions:
      contents: read
      id-token: write
      pages: write

    outputs:
      pmtiles_url: ${{ steps.upload-action.outputs.pmtiles_url }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: 'arn:aws:iam::910320664791:role/SmartcityStandaloneInfraA-SmartcityStandaloneInfraA-MlMTQc5HZbN7'
          aws-region: ap-northeast-1

      - name: Run this action
        id: upload-action
        uses: ./
        with:
          INPUT_DIR: './docs'
          MUNICIPALITY_CODE: '37201'
          NAME: 'smartcity-smartmap'

      - name: Smartmap
        run: |
          echo "下記のURLでプレビューを開けます"
          echo https://geolonia.github.io/smartcity-smartmap/#/?endpointUrl=${{ steps.upload-action.outputs.pmtiles_url }}
